import json

# Read notebook
with open('C:/users/colto/documents/github/tweet_project/arcgis_tweet_processor_complete.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find Cell 6 (Data Loading Functions) and replace it
for i, cell in enumerate(nb['cells']):
    if cell['cell_type'] == 'code' and 'DATA LOADING FUNCTIONS' in ''.join(cell.get('source', [])):
        print(f'Found Cell 6 at index {i}')
        cell['source'] = [
            '"""\n',
            'DATA LOADING FUNCTIONS\n',
            'GeoJSON from local path, everything else from GDB\n',
            '"""\n',
            '\n',
            'import json\n',
            '\n',
            'def load_tweets_geojson(workspace="in_memory"):\n',
            '    """\n',
            '    Load helene.geojson from LOCAL PATH by reading JSON and creating points\n',
            '    Returns: Feature class path\n',
            '    """\n',
            '    print("Loading tweets from helene.geojson...")\n',
            '    geojson_path = get_data_file_path(\'data\', \'geojson\', \'helene.geojson\')\n',
            '    print(f"  Path: {geojson_path}")\n',
            '\n',
            '    # Read GeoJSON file\n',
            '    with open(geojson_path, \'r\') as f:\n',
            '        geojson_data = json.load(f)\n',
            '\n',
            '    # Create feature class\n',
            '    tweets_fc = os.path.join(workspace, "tweets_helene")\n',
            '\n',
            '    # Create empty point feature class\n',
            '    arcpy.management.CreateFeatureclass(\n',
            '        os.path.dirname(tweets_fc) if workspace != "in_memory" else workspace,\n',
            '        os.path.basename(tweets_fc),\n',
            '        "POINT",\n',
            '        spatial_reference=arcpy.SpatialReference(4326)\n',
            '    )\n',
            '\n',
            '    # Add fields for attributes\n',
            '    arcpy.management.AddField(tweets_fc, "GPE", "TEXT", field_length=500)\n',
            '    arcpy.management.AddField(tweets_fc, "FAC", "TEXT", field_length=500)\n',
            '    arcpy.management.AddField(tweets_fc, "LOC", "TEXT", field_length=500)\n',
            '    arcpy.management.AddField(tweets_fc, "time", "TEXT", field_length=50)\n',
            '    arcpy.management.AddField(tweets_fc, "Latitude", "DOUBLE")\n',
            '    arcpy.management.AddField(tweets_fc, "Longitude", "DOUBLE")\n',
            '\n',
            '    # Insert features\n',
            '    fields = [\'SHAPE@XY\', \'GPE\', \'FAC\', \'LOC\', \'time\', \'Latitude\', \'Longitude\']\n',
            '\n',
            '    with arcpy.da.InsertCursor(tweets_fc, fields) as cursor:\n',
            '        for feature in geojson_data[\'features\']:\n',
            '            props = feature[\'properties\']\n',
            '            coords = feature[\'geometry\'][\'coordinates\']\n',
            '\n',
            '            # GeoJSON is [lon, lat]\n',
            '            lon = coords[0]\n',
            '            lat = coords[1]\n',
            '\n',
            '            cursor.insertRow([\n',
            '                (lon, lat),  # SHAPE@XY\n',
            '                props.get(\'GPE\', \'\'),\n',
            '                props.get(\'FAC\', \'\'),\n',
            '                props.get(\'LOC\', \'\'),\n',
            '                props.get(\'time\', \'\'),\n',
            '                lat,\n',
            '                lon\n',
            '            ])\n',
            '\n',
            '    count = int(arcpy.management.GetCount(tweets_fc).getOutput(0))\n',
            '    print(f"  ✓ Loaded {count} tweet features")\n',
            '\n',
            '    return tweets_fc\n',
            '\n',
            '\n',
            'def load_cities_csv(workspace="in_memory"):\n',
            '    """Load cities from GDB feature class"""\n',
            '    print("Loading cities from GDB...")\n',
            '    \n',
            '    cities_fc = os.path.join(workspace, "us_cities")\n',
            '    arcpy.management.CopyFeatures("cities1000", cities_fc)\n',
            '    \n',
            '    count = int(arcpy.management.GetCount(cities_fc).getOutput(0))\n',
            '    print(f"  ✓ Loaded {count} city features")\n',
            '    \n',
            '    return cities_fc\n',
            '\n',
            '\n',
            'def load_states_shapefile(workspace="in_memory"):\n',
            '    """Load states from GDB feature class"""\n',
            '    print("Loading states from GDB...")\n',
            '    \n',
            '    states_fc = os.path.join(workspace, "us_states")\n',
            '    arcpy.management.CopyFeatures("cb_2023_us_state_20m", states_fc)\n',
            '    \n',
            '    count = int(arcpy.management.GetCount(states_fc).getOutput(0))\n',
            '    print(f"  ✓ Loaded {count} state features")\n',
            '    \n',
            '    return states_fc\n',
            '\n',
            '\n',
            'def load_counties_shapefile(workspace="in_memory"):\n',
            '    """Load counties from GDB feature class"""\n',
            '    print("Loading counties from GDB...")\n',
            '    \n',
            '    counties_fc = os.path.join(workspace, "us_counties")\n',
            '    arcpy.management.CopyFeatures("cb_2023_us_county_20m", counties_fc)\n',
            '    \n',
            '    count = int(arcpy.management.GetCount(counties_fc).getOutput(0))\n',
            '    print(f"  ✓ Loaded {count} county features")\n',
            '    \n',
            '    return counties_fc\n',
            '\n',
            '\n',
            'print("✓ Data loading functions defined (GeoJSON from local, others from GDB).")'
        ]
        cell['outputs'] = [{
            'name': 'stdout',
            'output_type': 'stream',
            'text': ['✓ Data loading functions defined (GeoJSON from local, others from GDB).\n']
        }]
        cell['execution_count'] = 3
        break

# Write back
with open('C:/users/colto/documents/github/tweet_project/arcgis_tweet_processor_complete.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print('Successfully updated Cell 6: GeoJSON from local path, cities/states/counties from GDB')
